<?php
/**
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<li class="customer-status" data-bind="scope: 'customer'">
    <!-- ko if: customer().customer_status  -->
    <span class="customer-status"
          data-bind="text: new String('<?= $escaper->escapeHtml(__('Status: %1', '%1')) ?>').
              replace('%1', customer().customer_status)">
        </span>
    <!-- /ko -->
</li>

<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
</script>
